"""
Django settings for djangoProject project.

Generated by 'django-admin startproject' using Django 4.0rc1.

For more information on this file, see
https://docs.djangoproject1.com/en/dev/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject1.com/en/dev/ref/settings/
"""
import os.path
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
from django.conf.global_settings import SESSION_ENGINE

BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject1.com/en/dev/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fas)-xf-n#=s3todr^zm)6#7c7p@_^j$(0c$ab=49vk9)8kspk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app2.apps.App2Config',
    'tinymce',
    'djcelery',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'middle.app2.myMiddle',
]

ROOT_URLCONF = 'djangoProject1.urls'

TEMPLATES = [
    {
        'BACKEND' : 'django.template.backends.django.DjangoTemplates',
        'DIRS' : [BASE_DIR / 'templates']
        ,
        'APP_DIRS' : True,
        'OPTIONS' : {
            'context_processors' : [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangoProject1.wsgi.application'

# Database
# https://docs.djangoproject1.com/en/dev/ref/settings/#databases

DATABASES = {
    'default' : {
        'ENGINE' : 'django.db.backends.mysql',
        'NAME' : 'Ana1',
        'USER' : 'root',
        'PASSWORD' : '182515131',
        'HOST' : 'localhost',
        'PORT' : '3306',
    }
}

# Password validation
# https://docs.djangoproject1.com/en/dev/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME' : 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME' : 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME' : 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME' : 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject1.com/en/dev/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/dev/howto/static-files/

STATIC_URL = 'static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# 普通文件
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static'), ]  # 表示的是配置路径,对应的就是创建的静态文件目录
# SESSION_ENGINE='redis_session.session'
# SESSION_REDIS_PORT=6379
# SESSION_REDIS_DB=0
# SESSION_REDIS_PASSWORD='182515131'
# SESSION_REDIS_PREFIX='SESSION'
# 配置上传文件目录
MEDIA_ROOT = os.path.join(BASE_DIR, 'static/upfile')

# Default primary key field type
# https://docs.djangoproject1.com/en/dev/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 富文本
TINYMCE_DEFAULT_CONFIG = {
    'theme' : 'silver',
    'width' : 600,
    'height' : 400,
}

# celery
import djcelery
djcelery.setup_loader()  # 表示初始化队列
BROKER_URL = 'redis://Ana@127.0.0.1:6379/0'
CELERY_IMPORTS=('app2.task')